import type { SecretRealmDef } from '../../types'

/* ------------------------------------------------------------------ *
 * 剧情秘境：有向图配置。
 * 约定：startNode 必须指向 kind === 'entry' 的节点；终点 boss 的 to 为空数组。
 * from 只需列出全部前驱之一即可被进入（合流点允许被任一分支抵达）。
 * ------------------------------------------------------------------ */

/* ------------------------------ 一 · 青石村后山试炼 ------------------------------ */

const QINGSHI_TRIAL: SecretRealmDef = {
  id: 'realm_qingshi_trial',
  name: '青石村后山试炼',
  chapter: 1,
  desc: '后山旧祠前立着一块无字石。村里的老人说，走通它的人，才算真正踏上道途。',
  entryStage: 45,
  bg: '/images/bg-ink-mountains.png',
  startNode: 'qst_entry',
  nodes: [
    {
      id: 'qst_entry',
      kind: 'entry',
      name: '后山石径',
      desc: '一条被人踩了三十年的窄路，尽头分作两处：乱石坡与药丛深处。',
      from: [],
      to: ['qst_wolf', 'qst_herb'],
      reward: [{ type: 'give_cultivation', value: 120 }],
    },
    {
      id: 'qst_wolf',
      kind: 'battle',
      name: '乱石坡',
      desc: '一头青狼守着半副兽骨，骨上还留着旧年修士的牙印。',
      from: ['qst_entry'],
      to: ['qst_shrine'],
      monsterId: 'mob_qingshi_wolf',
      reward: [
        { type: 'give_stone', value: 150 },
        { type: 'give_cultivation', value: 420 },
      ],
    },
    {
      id: 'qst_herb',
      kind: 'treasure',
      name: '石缝灵草',
      desc: '石缝里积了一洼雨水，水边长着一株叶子发亮的草。',
      from: ['qst_entry'],
      to: ['qst_shrine'],
      reward: [
        { type: 'give_item', key: 'mat_jing_tie', count: 2 },
        { type: 'give_item', key: 'pill_juqi_dan', count: 1 },
      ],
    },
    {
      id: 'qst_shrine',
      kind: 'encounter',
      name: '雨夜破庙',
      desc: '破庙里火堆还没熄，有人比你先到这里，也比你伤得更重。',
      from: ['qst_wolf', 'qst_herb'],
      to: ['qst_altar', 'qst_cache'],
      storyId: 'e001_ruined_temple',
    },
    {
      id: 'qst_altar',
      kind: 'elite',
      name: '断碑残阵',
      desc: '半截石碑压着一座半废的引灵阵，阵眼里蹲着不知守了多少年的东西。',
      from: ['qst_shrine'],
      to: ['qst_boss', 'qst_spring'],
      monsterId: 'mob_qingshi_shou_kui',
      reward: [
        { type: 'give_stone', value: 260 },
        { type: 'give_cultivation', value: 640 },
      ],
    },
    {
      id: 'qst_cache',
      kind: 'treasure',
      name: '石龛遗物',
      desc: '供龛里的泥像塌了半边，像后塞着一件用麻布裹了多年的旧物。',
      from: ['qst_shrine'],
      to: ['qst_boss'],
      reward: [
        { type: 'give_equipment', quality: 'green', count: 1 },
        { type: 'give_cultivation', value: 300 },
      ],
    },
    {
      id: 'qst_spring',
      kind: 'treasure',
      name: '山泉灵眼',
      desc: '阵眼底下原是一汪活泉，水面上浮着一层极薄的灵气。',
      from: ['qst_altar'],
      to: ['qst_boss'],
      reward: [
        { type: 'give_cultivation', value: 900 },
        { type: 'give_item', key: 'pill_juqi_dan', count: 2 },
      ],
    },
    {
      id: 'qst_boss',
      kind: 'boss',
      name: '后山老蛟',
      desc: '祠后深潭翻起黑泥，一条老蛟抬起头来，眼里的光是冷的。',
      from: ['qst_altar', 'qst_cache', 'qst_spring'],
      to: [],
      monsterId: 'mob_qingshi_jiao',
      reward: [
        { type: 'give_stone', value: 600 },
        { type: 'give_cultivation', value: 1600 },
        { type: 'log', value: '老蛟沉回潭底。后山的风，第一次静了下来。' },
      ],
    },
  ],
  firstClear: [
    { type: 'give_treasure', key: 'tr_pochui_sword' },
    { type: 'give_cultivation', value: 3000 },
    { type: 'give_stone', value: 800 },
    { type: 'flag_set', key: 'realm_qingshi_trial_cleared', value: true },
    { type: 'log', value: '你走通了后山试炼，石碑上浮出第一道属于自己的刻痕。' },
  ],
}

/* ------------------------------ 二 · 黑风岭邪修洞府 ------------------------------ */

const HEIFENG_CAVE: SecretRealmDef = {
  id: 'realm_heifeng_cave',
  name: '黑风岭邪修洞府',
  chapter: 2,
  desc: '黑风道人死后，洞府里的血池仍未干。有人在里面接着做他没做完的事。',
  entryStage: 95,
  bg: '/images/bg-ink-mountains.png',
  startNode: 'hfc_entry',
  nodes: [
    {
      id: 'hfc_entry',
      kind: 'entry',
      name: '洞府石门',
      desc: '石门半开，门缝里渗出的血腥气被山风吹得忽浓忽淡。',
      from: [],
      to: ['hfc_guard', 'hfc_side'],
      reward: [{ type: 'give_cultivation', value: 200 }],
    },
    {
      id: 'hfc_guard',
      kind: 'battle',
      name: '门前守尸',
      desc: '两名邪修把活人炼成了守门的傀，见血便动。',
      from: ['hfc_entry'],
      to: ['hfc_hall'],
      monsterId: 'mob_heifeng_guard',
      reward: [
        { type: 'give_stone', value: 320 },
        { type: 'give_cultivation', value: 700 },
      ],
    },
    {
      id: 'hfc_side',
      kind: 'treasure',
      name: '洞壁暗龛',
      desc: '洞壁凿出一方暗龛，龛口封着干涸的符纸。',
      from: ['hfc_entry'],
      to: ['hfc_hall'],
      reward: [
        { type: 'give_item', key: 'mat_hei_tie', count: 3 },
        { type: 'give_stone', value: 240 },
      ],
    },
    {
      id: 'hfc_hall',
      kind: 'encounter',
      name: '血池中庭',
      desc: '一池暗红中泡着几具尚未沉底的躯壳，池边坐着个还在写字的人。',
      from: ['hfc_guard', 'hfc_side'],
      to: ['hfc_cells', 'hfc_refine'],
      storyId: 'hf_02_luoqi',
    },
    {
      id: 'hfc_cells',
      kind: 'encounter',
      name: '石牢怨声',
      desc: '牢门后没有活人，只有哭声在石缝里转了太久，散不掉。',
      from: ['hfc_hall'],
      to: ['hfc_beast'],
      storyId: 'e011_weeping_ghost',
      reward: [{ type: 'karma_add', key: 'daoHeart', value: 1 }],
    },
    {
      id: 'hfc_refine',
      kind: 'treasure',
      name: '废丹炉房',
      desc: '炉火早灭，炉膛里结着一层紫黑色的渣，渣中埋着几粒没被取走的丹。',
      from: ['hfc_hall'],
      to: ['hfc_beast'],
      reward: [
        { type: 'give_item', key: 'pill_baoxue_dan', count: 1 },
        { type: 'give_item', key: 'mat_chi_tong', count: 2 },
      ],
    },
    {
      id: 'hfc_beast',
      kind: 'elite',
      name: '豢兽深坑',
      desc: '坑底堆着断掉的铁链，与铁链一同长大的东西在黑暗里磨牙。',
      from: ['hfc_cells', 'hfc_refine'],
      to: ['hfc_altar', 'hfc_vault'],
      monsterId: 'mob_heifeng_beast',
      reward: [
        { type: 'give_stone', value: 520 },
        { type: 'give_cultivation', value: 1100 },
      ],
    },
    {
      id: 'hfc_vault',
      kind: 'treasure',
      name: '私藏石库',
      desc: '库门贴着七道封条，每一道都是同一个人的手笔。',
      from: ['hfc_beast'],
      to: ['hfc_altar'],
      reward: [
        { type: 'give_item', key: 'mat_ling_yin', count: 2 },
        { type: 'give_equipment', quality: 'blue', count: 1 },
      ],
    },
    {
      id: 'hfc_altar',
      kind: 'heritage',
      name: '血魂祭坛',
      desc: '坛上摊着一卷用人皮装订的册子，字是从血里养出来的。',
      from: ['hfc_beast', 'hfc_vault'],
      to: ['hfc_boss'],
      reward: [
        { type: 'give_technique', key: 'tech_xuehun_jing' },
        { type: 'karma_add', key: 'demonThought', value: 1 },
        { type: 'flag_set', key: 'heifeng_heritage_taken', value: true },
      ],
    },
    {
      id: 'hfc_boss',
      kind: 'boss',
      name: '黑风道人遗蜕',
      desc: '血池终于见底，池底站起来的东西穿着黑风道人的道袍，脸却不是他的。',
      from: ['hfc_altar'],
      to: [],
      monsterId: 'mob_heifeng_yitui',
      reward: [
        { type: 'give_stone', value: 1200 },
        { type: 'give_cultivation', value: 3200 },
        { type: 'log', value: '遗蜕倒下时，血池里的水一夜之间清了。' },
      ],
    },
  ],
  firstClear: [
    { type: 'give_treasure', key: 'tr_xuewen_drum' },
    { type: 'give_cultivation', value: 8000 },
    { type: 'give_stone', value: 2000 },
    { type: 'flag_set', key: 'realm_heifeng_cave_cleared', value: true },
    { type: 'log', value: '黑风岭的洞府再无声息，你在门口立了一块无字的木牌。' },
  ],
}

/* ------------------------------ 三 · 落霞古洞府 ------------------------------ */

const LUOXIA_CAVE: SecretRealmDef = {
  id: 'realm_luoxia_cave',
  name: '落霞古洞府',
  chapter: 4,
  desc: '红叶下压着一层旧阵。三百年间无人来过，药田里的草还在等人来锄。',
  entryStage: 170,
  bg: '/images/bg-ink-mountains.png',
  startNode: 'lx_entry',
  nodes: [
    {
      id: 'lx_entry',
      kind: 'entry',
      name: '洞府前庭',
      desc: '山壁裂开一道门。门内石桌塌了半边，桌上一只空碗，碗底积着三百年的灰。',
      from: [],
      to: ['lx_garden', 'lx_chamber'],
      reward: [{ type: 'give_cultivation', value: 300 }],
    },
    {
      id: 'lx_garden',
      kind: 'battle',
      name: '残破药园',
      desc: '荒了三百年的药田里，土还翻得动，翻土的东西却没走。',
      from: ['lx_entry'],
      to: ['lx_grave', 'lx_herb'],
      monsterId: 'mob_luoxia_yao_kui',
      reward: [
        { type: 'give_stone', value: 600 },
        { type: 'give_cultivation', value: 1400 },
      ],
    },
    {
      id: 'lx_chamber',
      kind: 'battle',
      name: '古修石室',
      desc: '石室里蒲团未散，蒲团前跪着一具穿着旧道袍的泥壳。',
      from: ['lx_entry'],
      to: ['lx_beastnest', 'lx_seal_room', 'lx_gui_pei'],
      monsterId: 'mob_luoxia_shishi_shou',
      reward: [
        { type: 'give_stone', value: 600 },
        { type: 'give_cultivation', value: 1400 },
      ],
    },
    {
      id: 'lx_grave',
      kind: 'encounter',
      name: '古修尸骨',
      desc: '药田尽头的石台上盘着一具枯骨，壁上刻着由深到浅的几行刀痕。',
      from: ['lx_garden'],
      to: ['lx_catacomb'],
      storyId: 'lx_01_ruins',
      reward: [
        { type: 'karma_add', key: 'daoHeart', value: 2 },
        { type: 'give_item', key: 'mat_xing_sha', count: 1 },
      ],
    },
    {
      id: 'lx_herb',
      kind: 'treasure',
      name: '药田残株',
      desc: '杂草深处竟还活着一株三花同开的旧株，是他生前留的种。',
      from: ['lx_garden'],
      to: ['lx_catacomb'],
      reward: [
        { type: 'give_item', key: 'mat_san_yang_hua', count: 1 },
        { type: 'give_item', key: 'mat_zhu_ji_ling_cao', count: 2 },
      ],
    },
    {
      id: 'lx_beastnest',
      kind: 'elite',
      name: '妖兽巢',
      desc: '巢里铺着的不是草，是历年走进洞府的人留下的东西。',
      from: ['lx_chamber'],
      to: ['lx_catacomb', 'lx_bone_pit'],
      monsterId: 'mob_luoxia_yao_chao_zhu',
      reward: [
        { type: 'give_stone', value: 900 },
        { type: 'give_cultivation', value: 2000 },
        { type: 'give_item', key: 'mat_yao_gu', count: 2 },
      ],
    },
    {
      id: 'lx_seal_room',
      kind: 'treasure',
      name: '封灵暗室',
      desc: '门上封着七道早失效的禁制，室内的东西却一样没少。',
      from: ['lx_chamber'],
      to: ['lx_catacomb'],
      reward: [
        { type: 'give_item', key: 'mat_di_mai_shi', count: 2 },
        { type: 'give_equipment', quality: 'purple', count: 1 },
      ],
    },
    {
      id: 'lx_gui_pei',
      kind: 'treasure',
      name: '丹房药柜',
      desc: '药柜倒了，抽屉散在地上，几枚蜡封的丹丸滚到墙角。',
      from: ['lx_chamber'],
      to: ['lx_catacomb'],
      reward: [
        { type: 'give_item', key: 'pill_zhuji_lingye', count: 2 },
        { type: 'give_stone', value: 700 },
      ],
    },
    {
      id: 'lx_catacomb',
      kind: 'elite',
      name: '地宫尸廊',
      desc: '地宫长廊两侧嵌满了壁龛，壁龛里的东西听到脚步便转过头来。',
      from: ['lx_grave', 'lx_herb', 'lx_beastnest', 'lx_seal_room', 'lx_gui_pei'],
      to: ['lx_bone_pit', 'lx_swordstele'],
      monsterId: 'mob_luoxia_digong_kui',
      reward: [
        { type: 'give_stone', value: 1000 },
        { type: 'give_cultivation', value: 2400 },
      ],
    },
    {
      id: 'lx_bone_pit',
      kind: 'treasure',
      name: '枯骨堆',
      desc: '一堆被仔细收拢过的枯骨，骨缝里卡着半枚断掉的玉。',
      from: ['lx_beastnest', 'lx_catacomb'],
      to: ['lx_swordstele'],
      reward: [
        { type: 'give_item', key: 'mat_di_mai_ling_sui', count: 1 },
        { type: 'karma_add', key: 'jadeResonance', value: 1 },
      ],
    },
    {
      id: 'lx_swordstele',
      kind: 'heritage',
      name: '剑碑残章',
      desc: '石台上立着一块无字剑碑。你的手刚碰上碑面，碑上便起了一层细霜。',
      from: ['lx_catacomb', 'lx_bone_pit'],
      to: ['lx_jade_pool', 'lx_xie'],
      storyId: 'lx_02_stele',
      reward: [
        { type: 'give_technique', key: 'tech_wuming_jianzhang' },
        { type: 'flag_set', key: 'luoxia_stele_read', value: true },
        { type: 'log', value: '无名剑章·上卷入识海。碑上依旧无字。' },
      ],
    },
    {
      id: 'lx_jade_pool',
      kind: 'encounter',
      name: '古玉共鸣',
      desc: '碑后一汪石泉。你贴身那枚玉忽然发烫，泉水跟着亮了一线。',
      from: ['lx_swordstele'],
      to: ['lx_ward'],
      storyId: 'e002_broken_stele',
      reward: [
        { type: 'karma_add', key: 'jadeResonance', value: 2 },
        { type: 'give_item', key: 'mat_di_mai_ling_sui', count: 1 },
      ],
    },
    {
      id: 'lx_xie',
      kind: 'encounter',
      name: '谢无尘夺碑',
      desc: '碑前多了一个人。他看碑的眼神比你熟，也比你要狠。',
      from: ['lx_swordstele'],
      to: ['lx_ward'],
      storyId: 'lx_03_xiewuchen',
      reward: [
        { type: 'flag_set', key: 'luoxia_xie_met', value: true },
        { type: 'relation_add', key: 'xie_wuchen', value: 4 },
      ],
    },
    {
      id: 'lx_ward',
      kind: 'battle',
      name: '地龙甬道',
      desc: '甬道尽头的地面是活的。石缝里渗出的甲壳一片片翻起来。',
      from: ['lx_jade_pool', 'lx_xie'],
      to: ['lx_old_cache', 'lx_dragon'],
      monsterId: 'mob_luoxia_shi_jia_chong',
      reward: [
        { type: 'give_stone', value: 1400 },
        { type: 'give_cultivation', value: 3000 },
      ],
    },
    {
      id: 'lx_old_cache',
      kind: 'treasure',
      name: '落霞旧藏',
      desc: '甬道侧壁被地龙拱开一道口子，里面是三百年没人动过的旧箱。',
      from: ['lx_ward'],
      to: ['lx_dragon'],
      reward: [
        { type: 'give_item', key: 'mat_di_mai_ling_sui', count: 1 },
        { type: 'give_treasure', key: 'tr_zhenhun_bell' },
        { type: 'karma_add', key: 'jadeShards', value: 1 },
      ],
    },
    {
      id: 'lx_dragon',
      kind: 'boss',
      name: '石甲地龙',
      desc: '整座洞府的地脉都盘在它身上。它一动，药园的药草齐齐向南伏倒。',
      from: ['lx_ward', 'lx_old_cache'],
      to: [],
      monsterId: 'mob_luoxia_shi_jia_di_long',
      reward: [
        { type: 'give_stone', value: 3000 },
        { type: 'give_cultivation', value: 9000 },
        { type: 'give_item', key: 'mat_di_mai_ling_sui', count: 2 },
        { type: 'karma_add', key: 'daoHeart', value: 1 },
        { type: 'log', value: '地龙伏地不动。你脚下的地脉，终于顺了过来。' },
      ],
    },
  ],
  firstClear: [
    { type: 'give_technique', key: 'tech_wuming_jianzhang' },
    { type: 'give_treasure', key: 'tr_canpo_guyu' },
    { type: 'give_item', key: 'mat_di_mai_ling_sui', count: 2 },
    { type: 'give_cultivation', value: 24000 },
    { type: 'give_stone', value: 6000 },
    { type: 'karma_add', key: 'jadeResonance', value: 2 },
    { type: 'flag_set', key: 'realm_luoxia_cave_cleared', value: true },
    { type: 'log', value: '落霞洞府首通。你把那位古修的名字刻上了剑碑，碑上终于有了第一行字。' },
  ],
}

export const SECRET_REALMS: SecretRealmDef[] = [
  QINGSHI_TRIAL,
  HEIFENG_CAVE,
  LUOXIA_CAVE,
]

export const SECRET_REALM_BY_ID: Record<string, SecretRealmDef> = Object.fromEntries(
  SECRET_REALMS.map((r) => [r.id, r]),
)
