import type { PetDef } from '../types'

/* ------------------------------------------------------------------ *
 * 15 只灵兽（PRD 21 章）
 * passive 为常驻加成，随灵兽境界成长；skill 为出战时自动施放。
 * 治疗效果以自身攻击为基（scale × ATK），因此治疗型灵兽也吃攻击加成。
 * ------------------------------------------------------------------ */
export const PETS: PetDef[] = [
  {
    id: 'pet_qingling_fox',
    name: '青灵狐',
    quality: 'green',
    icon: 'fox',
    skill: {
      cast: 'heal',
      damageType: 'wood',
      scale: 1.4,
      cooldown: 12,
      desc: '口吐青灵之气，为主人回复生命并驱散一层负面。',
    },
    passive: { hp: 300, hpRegen: 0.004 },
    desc: '苍梧古林常见的幼狐，性温顺，最善疗伤。',
  },
  {
    id: 'pet_leiyu_eagle',
    name: '雷羽鹰',
    quality: 'blue',
    icon: 'eagle',
    skill: {
      cast: 'aoe',
      damageType: 'metal',
      scale: 1.6,
      cooldown: 10,
      desc: '展翼扑击，雷羽如箭，对范围内敌人造成雷属性伤害。',
    },
    passive: { metalDmg: 0.06 },
    desc: '生于五雷山绝壁，羽尖终年缠着一线电光。',
  },
  {
    id: 'pet_xuanjia_turtle',
    name: '玄甲龟',
    quality: 'blue',
    icon: 'tortoise',
    skill: {
      cast: 'shield',
      damageType: 'earth',
      scale: 1.2,
      cooldown: 14,
      desc: '龟息凝甲，为主人展开一层土灵护盾。',
    },
    passive: { def: 40, dmgReduction: 0.03 },
    desc: '甲纹如玄文，负甲千年而不动，故称玄甲。',
  },
  {
    id: 'pet_chiyan_tiger',
    name: '赤焰虎',
    quality: 'purple',
    icon: 'tiger',
    skill: {
      cast: 'aoe',
      damageType: 'fire',
      scale: 2.2,
      cooldown: 12,
      desc: '扑杀之时焰从口出，对两名敌人造成火属性爆发伤害。',
    },
    passive: { atk: 45, critDmg: 0.08 },
    desc: '赤炎秘境中的虎妖幼崽，一出世便带着火脉。',
  },
  {
    id: 'pet_shihun_crow',
    name: '噬魂鸦',
    quality: 'purple',
    icon: 'crow',
    skill: {
      cast: 'dot',
      damageType: 'soul',
      scale: 1.5,
      cooldown: 9,
      desc: '群鸦啄魂，使目标持续流失生命并降低回复。',
    },
    passive: { dotDmg: 0.07 },
    desc: '幽冥谷中食魂而生的黑鸦，叫声令人心头发冷。',
  },
  {
    id: 'pet_qingmu_deer',
    name: '青木鹿',
    quality: 'blue',
    icon: 'deer',
    skill: {
      cast: 'heal',
      damageType: 'wood',
      scale: 1.8,
      cooldown: 8,
      desc: '鹿角散出木灵，持续为主人回复生命。',
    },
    passive: { hp: 200, hpRegen: 0.008 },
    desc: '百草谷放养的灵鹿，角上常年开着细小白花。',
  },
  {
    id: 'pet_hanyue_wolf',
    name: '寒月狼',
    quality: 'blue',
    icon: 'wolf',
    skill: {
      cast: 'aoe',
      damageType: 'water',
      scale: 1.5,
      cooldown: 10,
      desc: '嗥声引来寒霜，冻伤并减缓敌人的行动。',
    },
    passive: { waterDmg: 0.06, eva: 0.02 },
    desc: '极北冰原的狼群头目，皮毛上凝着一层不化的霜。',
  },
  {
    id: 'pet_yanjia_rhino',
    name: '岩甲犀',
    quality: 'purple',
    icon: 'rhino',
    skill: {
      cast: 'shield',
      damageType: 'earth',
      scale: 1.3,
      cooldown: 13,
      desc: '以身为盾挡在主人身前，减免接下来受到的伤害。',
    },
    passive: { dmgReduction: 0.045 },
    desc: '奔行时大地随之震颤，皮上碎石层层相叠如甲。',
  },
  {
    id: 'pet_jinling_crane',
    name: '金翎鹤',
    quality: 'orange',
    icon: 'crane',
    skill: {
      cast: 'buff',
      damageType: 'metal',
      scale: 1.2,
      cooldown: 12,
      desc: '清唳一声，金翎之光入体，提升主人暴击与暴伤。',
    },
    passive: { crit: 0.04, critDmg: 0.1 },
    desc: '仙鹤遗种，金翎一展，凡剑亦生锋锐之意。',
  },
  {
    id: 'pet_yingdiao',
    name: '影貂',
    quality: 'orange',
    icon: 'marten',
    skill: {
      cast: 'buff',
      damageType: 'true',
      scale: 1.2,
      cooldown: 11,
      desc: '化作一道残影绕身而行，短时间大幅提升闪避与攻速。',
    },
    passive: { eva: 0.05, aspd: 0.08 },
    desc: '来去无声的灵貂，连元婴修士都难捕捉它的行踪。',
  },
  {
    id: 'pet_lingzhu_bear',
    name: '灵竹熊',
    quality: 'orange',
    icon: 'bear',
    skill: {
      cast: 'shield',
      damageType: 'wood',
      scale: 1.5,
      cooldown: 15,
      desc: '竹影成壁，为主人附加厚盾并缠住最近的敌人。',
    },
    passive: { hp: 400, shieldPower: 0.08 },
    desc: '苍梧古林深处的食铁兽，皮糙肉厚却性子温和。',
  },
  {
    id: 'pet_hailin_beast',
    name: '海麟兽',
    quality: 'red',
    icon: 'seabeast',
    skill: {
      cast: 'aoe',
      damageType: 'water',
      scale: 1.7,
      cooldown: 12,
      desc: '掀浪成潮，对全体敌人造成水属性伤害并降低其元素抗性。',
    },
    passive: { waterDmg: 0.07, dmgReduction: 0.03 },
    desc: '无尽海中的异兽，鳞上有天然的水灵纹，能避百邪。',
  },
  {
    id: 'pet_guling_hound',
    name: '骨灵犬',
    quality: 'red',
    icon: 'hound',
    skill: {
      cast: 'summon',
      damageType: 'soul',
      scale: 1.6,
      cooldown: 10,
      desc: '一啸召出两只骨犬随行，与主人召唤物协同撕咬。',
    },
    passive: { atk: 30, summonDmg: 0.08 },
    desc: '万骨荒原上的亡犬，认主之后便世世跟随。',
  },
  {
    id: 'pet_xingwen_butterfly',
    name: '星纹蝶',
    quality: 'purple',
    icon: 'butterfly',
    skill: {
      cast: 'buff',
      damageType: 'true',
      scale: 1.2,
      cooldown: 16,
      desc: '振翅落下星尘，使主人所有法宝冷却缩短。',
    },
    passive: { cdr: 0.05 },
    desc: '星砂之力凝成的蝶，翅上纹路与天上星图一致。',
  },
  {
    id: 'pet_xiao_baize',
    name: '小白泽',
    quality: 'rainbow',
    icon: 'baize',
    skill: {
      cast: 'buff',
      damageType: 'true',
      scale: 1.2,
      cooldown: 20,
      desc: '低鸣示警，短时间大幅提升主人机缘，使奇遇与稀有掉落更易出现。',
    },
    passive: { rareDropRate: 0.06, dropRate: 0.04, idleCultivation: 0.05 },
    desc: '通晓万物之名的瑞兽，知天下异动，遇之则有大机缘。',
  },
]

export const PET_BY_ID: Record<string, PetDef> = Object.fromEntries(
  PETS.map((p) => [p.id, p]),
)

/** 必须通过事件链认主、不可直接抽取的灵兽 */
export const PET_EVENT_ONLY = ['pet_qingling_fox', 'pet_xiao_baize', 'pet_guling_hound']
