import type { TechniqueDef } from '../types'

/* ------------------------------------------------------------------ *
 * 功法 24 本（PRD 17 章）+ 旧 UI 已展示的 5 本同系功法（共 29 条）
 * 每系前两本为主修（role: 'main'），其余为辅助；主修 maxLevel 15~20，
 * 辅助 maxLevel 10。perLevel 数值刻意克制：攻击类每级约 8~24 点固定值
 * 或 1.2%~2% 百分比，避免十级堆出翻倍战力。
 * ------------------------------------------------------------------ */
export const TECHNIQUES: TechniqueDef[] = [
  /* ------------------------------ 剑修 ------------------------------ */
  {
    id: 'tech_yujian_jue',
    name: '御剑诀',
    school: 'sword',
    quality: 'green',
    icon: 'sword',
    role: 'main',
    desc: '青玄剑宗入门剑诀，以气御剑，剑随念走。',
    perLevel: { atk: 8, swordDmg: 0.012 },
    maxLevel: 20,
  },
  {
    id: 'tech_jianxin_jue',
    name: '剑心诀',
    school: 'sword',
    quality: 'blue',
    icon: 'crit',
    role: 'support',
    desc: '剑心通明，出剑时自寻敌之破绽。',
    perLevel: { crit: 0.003, critDmg: 0.006 },
    maxLevel: 10,
  },
  {
    id: 'tech_taixu_jianjing',
    name: '太虚剑经',
    school: 'sword',
    quality: 'orange',
    icon: 'array',
    role: 'main',
    desc: '太虚一脉不传之秘，剑意为阵，阵起则万剑同鸣。',
    perLevel: { atk: 14, swordDmg: 0.016, cdr: 0.002 },
    maxLevel: 20,
  },
  {
    id: 'tech_wuming_jianzhang',
    name: '无名剑章',
    school: 'sword',
    quality: 'purple',
    icon: 'book',
    role: 'main',
    desc: '落霞剑碑所刻残章，无招式之名，只有一线剑意。随剧情补全后自行成长。',
    perLevel: { atk: 12, critDmg: 0.01 },
    maxLevel: 15,
  },
  {
    id: 'tech_pojun_jiandian',
    name: '破军剑典',
    school: 'sword',
    quality: 'purple',
    icon: 'spear',
    role: 'support',
    desc: '专为斩将而创，一剑破甲，再剑破势。',
    perLevel: { pen: 0.004, bossDmg: 0.008 },
    maxLevel: 10,
  },
  {
    id: 'tech_wanjian_guiyi',
    name: '万剑归一诀',
    school: 'sword',
    quality: 'red',
    icon: 'sword',
    role: 'support',
    desc: '弃剑数而求剑质，万剑只余一柄，一柄可断山河。',
    perLevel: { swordDmg: 0.02, aspd: 0.004, critDmg: 0.008 },
    maxLevel: 10,
  },
  {
    id: 'tech_qingyuan_jianjue',
    name: '青元剑诀',
    school: 'sword',
    quality: 'purple',
    icon: 'book',
    role: 'support',
    desc: '剑气如虹，斩妖除邪。青元一脉以剑气温养肉身，久修不伤本元。',
    perLevel: { swordDmg: 0.012, crit: 0.002 },
    maxLevel: 10,
  },
  {
    id: 'tech_qingfeng_jianyi',
    name: '清风剑意',
    school: 'sword',
    quality: 'green',
    icon: 'wind',
    role: 'support',
    desc: '剑随心动，快若清风。以快制慢，以意御形。',
    perLevel: { aspd: 0.006, eva: 0.002 },
    maxLevel: 10,
  },

  /* ------------------------------ 法修 ------------------------------ */
  {
    id: 'tech_wulei_zhenjue',
    name: '五雷真诀',
    school: 'spell',
    quality: 'orange',
    icon: 'thunder',
    role: 'main',
    desc: '五雷山正宗雷法，引天雷覆万敌，雷落处草木皆焦。',
    perLevel: { metalDmg: 0.016, spellDmg: 0.014, atk: 10 },
    maxLevel: 20,
  },
  {
    id: 'tech_lihuo_jing',
    name: '离火经',
    school: 'spell',
    quality: 'blue',
    icon: 'flame',
    role: 'main',
    desc: '离为火，火曰炎上。灼烧不灭，直至敌成灰烬。',
    perLevel: { fireDmg: 0.016, spellDmg: 0.01 },
    maxLevel: 15,
  },
  {
    id: 'tech_xuanshui_jue',
    name: '玄水诀',
    school: 'spell',
    quality: 'blue',
    icon: 'water',
    role: 'support',
    desc: '上善若水，水势无形。可滞敌行，可润己身。',
    perLevel: { waterDmg: 0.014, cdr: 0.002 },
    maxLevel: 10,
  },
  {
    id: 'tech_qingmu_changsheng',
    name: '青木长生功',
    school: 'spell',
    quality: 'green',
    icon: 'wood',
    role: 'support',
    desc: '百草谷养生之法，木气不绝，伤势自愈。',
    perLevel: { hp: 60, woodDmg: 0.012, hpRegen: 0.002 },
    maxLevel: 10,
  },
  {
    id: 'tech_houtu_xuangong',
    name: '厚土玄功',
    school: 'spell',
    quality: 'blue',
    icon: 'earth',
    role: 'support',
    desc: '厚德载物，土不可摧。攻守之间，自成一方天地。',
    perLevel: { def: 8, earthDmg: 0.014, dmgReduction: 0.002 },
    maxLevel: 10,
  },
  {
    id: 'tech_wuxing_lunzhuan',
    name: '五行轮转经',
    school: 'spell',
    quality: 'red',
    icon: 'cycle',
    role: 'main',
    desc: '五行相生相克，轮转不休。修至极处，术法无相。',
    perLevel: {
      spellDmg: 0.02,
      metalDmg: 0.006,
      fireDmg: 0.006,
      waterDmg: 0.006,
      woodDmg: 0.006,
      earthDmg: 0.006,
    },
    maxLevel: 15,
  },
  {
    id: 'tech_lihuo_fentian',
    name: '离火焚天诀',
    school: 'spell',
    quality: 'orange',
    icon: 'flame',
    role: 'main',
    desc: '离火燎原，焚尽八荒。烈焰缠身者，纵逃亦成飞灰。',
    perLevel: { fireDmg: 0.018, dotDmg: 0.014 },
    maxLevel: 15,
  },

  /* ------------------------------ 体修 ------------------------------ */
  {
    id: 'tech_jinshen_jue',
    name: '金身诀',
    school: 'body',
    quality: 'blue',
    icon: 'shield',
    role: 'main',
    desc: '镇岳门筑基炼体之法，皮膜如铁，血气如沸。',
    perLevel: { hp: 120, dmgReduction: 0.003 },
    maxLevel: 15,
  },
  {
    id: 'tech_zhenyue_gong',
    name: '镇岳功',
    school: 'body',
    quality: 'purple',
    icon: 'mountain',
    role: 'main',
    desc: '立身如岳，人打我不动，我动人不存。',
    perLevel: { def: 14, thorn: 0.004, shieldPower: 0.006 },
    maxLevel: 20,
  },
  {
    id: 'tech_longxiang_liti',
    name: '龙象炼体诀',
    school: 'body',
    quality: 'orange',
    icon: 'dragon',
    role: 'main',
    desc: '力可担山，吼可裂石。体修入门的极境，便是化凡躯为龙象。',
    perLevel: { hp: 180, atk: 10 },
    maxLevel: 20,
  },
  {
    id: 'tech_bumie_gujing',
    name: '不灭骨经',
    school: 'body',
    quality: 'purple',
    icon: 'bone',
    role: 'support',
    desc: '炼骨如炼器，骨不断则人不灭，伤愈之后更胜从前。',
    perLevel: { hp: 100, hpRegen: 0.003 },
    maxLevel: 10,
  },
  {
    id: 'tech_shanhe_duanti',
    name: '山河锻体术',
    school: 'body',
    quality: 'blue',
    icon: 'hammer',
    role: 'support',
    desc: '以地脉之力反复捶打肉身，痛一分，硬一分。',
    perLevel: { def: 10, shieldPower: 0.008 },
    maxLevel: 10,
  },
  {
    id: 'tech_xuangui_xifa',
    name: '玄龟息法',
    school: 'body',
    quality: 'green',
    icon: 'tortoise',
    role: 'support',
    desc: '龟伏千年，一息而已。屏息之间，外伤自敛。',
    perLevel: { dmgReduction: 0.003, eva: 0.002 },
    maxLevel: 10,
  },
  {
    id: 'tech_xuanwu_jinshen',
    name: '玄武金身诀',
    school: 'body',
    quality: 'blue',
    icon: 'shield',
    role: 'main',
    desc: '肉身如岳，不动如山。玄武镇水，亦镇此身。',
    perLevel: { def: 12, dmgReduction: 0.004 },
    maxLevel: 15,
  },

  /* ------------------------------ 魔修 ------------------------------ */
  {
    id: 'tech_xuehun_jing',
    name: '血魂经',
    school: 'demon',
    quality: 'purple',
    icon: 'blood',
    role: 'main',
    desc: '以血养魂，以魂御血。幽冥谷入门魔功，伤敌一分，补己一分。',
    perLevel: { atk: 10, lifesteal: 0.004 },
    maxLevel: 20,
  },
  {
    id: 'tech_shehun_shu',
    name: '摄魂术',
    school: 'demon',
    quality: 'blue',
    icon: 'soul',
    role: 'support',
    desc: '摄魂夺魄，反哺己身。所摄之魂，皆为驱使。',
    perLevel: { dotDmg: 0.012, summonDmg: 0.008 },
    maxLevel: 10,
  },
  {
    id: 'tech_youming_jue',
    name: '幽冥诀',
    school: 'demon',
    quality: 'purple',
    icon: 'lamp',
    role: 'main',
    desc: '幽灯照魂，蚀而不陨。受此诀者，伤口不肯愈合。',
    perLevel: { dotDmg: 0.016, pen: 0.003 },
    maxLevel: 15,
  },
  {
    id: 'tech_shihun_jue',
    name: '噬魂诀',
    school: 'demon',
    quality: 'red',
    icon: 'skull',
    role: 'support',
    desc: '吞魂噬念，越战越强。每有魂灭，便多一分噬魂之力。',
    perLevel: { dotDmg: 0.018, lifesteal: 0.003, atk: 12 },
    maxLevel: 10,
  },
  {
    id: 'tech_ranshou_modian',
    name: '燃寿魔典',
    school: 'demon',
    quality: 'orange',
    icon: 'candle',
    role: 'main',
    desc: '燃已寿元，换一时之威。魔修最盛处，亦是寿命最短处。',
    perLevel: { atk: 24, aspd: 0.006 },
    maxLevel: 15,
  },
  {
    id: 'tech_jinghun_nijing',
    name: '净魂逆经',
    school: 'demon',
    quality: 'rainbow',
    icon: 'purify',
    role: 'support',
    desc: '幽冥谷抗仙蚀一派的逆行之经，将污染的神魂一寸寸剥离。',
    perLevel: { dotDmg: 0.014, dmgReduction: 0.004, hpRegen: 0.003 },
    maxLevel: 10,
  },
  {
    id: 'tech_xuesha_mogong',
    name: '血煞魔功',
    school: 'demon',
    quality: 'red',
    icon: 'blood',
    role: 'main',
    desc: '以血为引，吞噬生机。煞气入体者，往往再难回头。',
    perLevel: { atk: 14, lifesteal: 0.005 },
    maxLevel: 15,
  },
]

export const TECHNIQUE_BY_ID: Record<string, TechniqueDef> = Object.fromEntries(
  TECHNIQUES.map((t) => [t.id, t]),
)

/** 每系主修功法，供 Build 面板默认推荐 */
export const MAIN_TECHNIQUES: Record<string, string[]> = {
  sword: ['tech_yujian_jue', 'tech_taixu_jianjing', 'tech_wuming_jianzhang'],
  spell: ['tech_wulei_zhenjue', 'tech_lihuo_jing', 'tech_wuxing_lunzhuan'],
  body: ['tech_jinshen_jue', 'tech_zhenyue_gong', 'tech_longxiang_liti'],
  demon: ['tech_xuehun_jing', 'tech_youming_jue', 'tech_ranshou_modian'],
}
