import type { TreasureDef } from '../types'

/* ------------------------------------------------------------------ *
 * 30 件法宝（PRD 16 章）
 * cast 决定战斗表现：飞剑/直线 → projectile；剑阵/群体 → aoe；
 * 护体/减伤 → shield；召魂/骨傀 → summon；灼烧/魂蚀 → dot；
 * 疗伤 → heal；自身增益与复制 → buff；不施放的常驻效果 → aura。
 * scale 与 cooldown 一般成反比：cd ≤ 8 的倍率压在 1.2~2.0，
 * cd ≥ 14 的允许 2.4~3.8，保证单位时间收益大致同阶。
 * ------------------------------------------------------------------ */
export const TREASURES: TreasureDef[] = [
  /* ------------------------------ 剑修 5 ------------------------------ */
  {
    id: 'tr_qingxiao_sword',
    name: '青霄飞剑',
    kind: 'active',
    cast: 'projectile',
    damageType: 'physical',
    scale: 1.8,
    cooldown: 3.5,
    initialCd: 0.5,
    quality: 'blue',
    icon: 'sword',
    desc: '御剑千里，取敌首级。对单体造成 180% 攻击伤害，暴击时飞剑回旋再斩一次。',
    unlockStage: 10,
  },
  {
    id: 'tr_qiyao_case',
    name: '七曜剑匣',
    kind: 'active',
    cast: 'summon',
    damageType: 'physical',
    scale: 2.2,
    cooldown: 9,
    quality: 'purple',
    icon: 'case',
    targets: 3,
    duration: 6,
    desc: '剑匣七曜轮转，每息自行吐出一柄飞剑追击敌人，持续六息。',
    unlockStage: 30,
  },
  {
    id: 'tr_taixu_array',
    name: '太虚剑阵',
    kind: 'active',
    cast: 'aoe',
    damageType: 'physical',
    scale: 1.35,
    cooldown: 12,
    quality: 'orange',
    icon: 'array',
    targets: 5,
    duration: 6,
    desc: '剑意化阵，覆盖一方。阵中每息对最多五名敌人造成 135% 伤害。',
    unlockStage: 120,
  },
  {
    id: 'tr_pochui_sword',
    name: '破云剑',
    kind: 'active',
    cast: 'projectile',
    damageType: 'physical',
    scale: 2.6,
    cooldown: 8,
    quality: 'blue',
    icon: 'sword',
    desc: '一剑破云，贯穿直线。造成 260% 伤害并穿透目标 40% 防御。',
    unlockStage: 60,
  },
  {
    id: 'tr_wanjian_map',
    name: '万剑图',
    kind: 'active',
    cast: 'aoe',
    damageType: 'physical',
    scale: 3.2,
    cooldown: 18,
    quality: 'red',
    icon: 'scroll',
    targets: 6,
    desc: '展开剑图，按场上剑意层数唤落剑雨。基础 320%，每层剑意额外增幅。',
    unlockStage: 260,
  },

  /* ------------------------------ 法修 5 ------------------------------ */
  {
    id: 'tr_jiuxiao_thunder',
    name: '九霄雷符',
    kind: 'active',
    cast: 'aoe',
    damageType: 'metal',
    scale: 2.4,
    cooldown: 12,
    quality: 'purple',
    icon: 'thunder',
    targets: 4,
    desc: '朱笔引雷，天威浩荡。对至多四名敌人降下 240% 雷击，并连锁至相邻敌人。',
    unlockStage: 30,
  },
  {
    id: 'tr_chiyan_orb',
    name: '赤焰珠',
    kind: 'active',
    cast: 'aoe',
    damageType: 'fire',
    scale: 2.0,
    cooldown: 9,
    quality: 'blue',
    icon: 'flame',
    targets: 3,
    duration: 5,
    desc: '珠落成焰，轰然炸开。对三名敌人造成 200% 火伤并附加灼烧。',
    unlockStage: 20,
  },
  {
    id: 'tr_hanyue_wheel',
    name: '寒月轮',
    kind: 'active',
    cast: 'aoe',
    damageType: 'water',
    scale: 1.6,
    cooldown: 7,
    quality: 'green',
    icon: 'moon',
    targets: 3,
    duration: 4,
    desc: '冰刃回旋，触之滞涩。造成 160% 水伤并降低敌人攻速与移速。',
    unlockStage: 10,
  },
  {
    id: 'tr_wuxing_seal',
    name: '五行玄印',
    kind: 'active',
    cast: 'aoe',
    damageType: 'true',
    scale: 2.6,
    cooldown: 14,
    quality: 'orange',
    icon: 'seal',
    targets: 4,
    desc: '印随心动，五行易位。伤害属性自动转为自身最高的那一行元素。',
    unlockStage: 90,
  },
  {
    id: 'tr_xuanshui_bottle',
    name: '玄水瓶',
    kind: 'active',
    cast: 'shield',
    damageType: 'water',
    scale: 1.4,
    cooldown: 14,
    quality: 'white',
    icon: 'bottle',
    duration: 8,
    desc: '倾瓶洒水，润物无声。为自身附加水幕护盾，护盾存在时受击反弹水伤。',
    unlockStage: 8,
  },

  /* ------------------------------ 体修 5 ------------------------------ */
  {
    id: 'tr_zhenyue_seal',
    name: '镇岳印',
    kind: 'active',
    cast: 'aoe',
    damageType: 'earth',
    scale: 2.8,
    cooldown: 13,
    quality: 'green',
    icon: 'seal',
    targets: 3,
    duration: 2,
    desc: '印如山岳压顶。对三名敌人造成 280% 伤害并使其短暂昏眩。',
    unlockStage: 10,
  },
  {
    id: 'tr_jingang_bell',
    name: '金刚钟',
    kind: 'active',
    cast: 'shield',
    damageType: 'earth',
    scale: 1.5,
    cooldown: 16,
    quality: 'blue',
    icon: 'bell',
    duration: 10,
    desc: '钟鸣护体，外邪难侵。获得护盾并在一段时间内提升减伤。',
    unlockStage: 20,
  },
  {
    id: 'tr_xuangui_shell',
    name: '玄龟甲',
    kind: 'passive',
    cast: 'aura',
    damageType: 'earth',
    scale: 0,
    cooldown: 0,
    quality: 'blue',
    icon: 'tortoise',
    desc: '常驻减伤 12%；生命低于三成时，额外再减伤一成。',
    unlockStage: 20,
  },
  {
    id: 'tr_xuewen_drum',
    name: '血纹战鼓',
    kind: 'active',
    cast: 'buff',
    damageType: 'physical',
    scale: 1.2,
    cooldown: 20,
    quality: 'purple',
    icon: 'drum',
    duration: 8,
    desc: '击鼓以血为祭，燃去自身一成生命，换取攻速与攻击大幅提升。',
    unlockStage: 40,
  },
  {
    id: 'tr_shanhe_cauldron',
    name: '山河鼎',
    kind: 'active',
    cast: 'shield',
    damageType: 'earth',
    scale: 2.2,
    cooldown: 15,
    quality: 'orange',
    icon: 'cauldron',
    duration: 6,
    desc: '鼎纳山河，蓄势而反。吸收受到的伤害，到期后一次性回敬敌人。',
    unlockStage: 70,
  },

  /* ------------------------------ 魔修 5 ------------------------------ */
  {
    id: 'tr_shehun_banner',
    name: '摄魂幡',
    kind: 'active',
    cast: 'summon',
    damageType: 'soul',
    scale: 2.0,
    cooldown: 11,
    quality: 'blue',
    icon: 'banner',
    targets: 2,
    duration: 8,
    desc: '幡动魂来，召出两道怨魂缠斗，每命中一次为自身叠加一层魂印。',
    unlockStage: 30,
  },
  {
    id: 'tr_xuehun_orb',
    name: '血魂珠',
    kind: 'active',
    cast: 'aoe',
    damageType: 'soul',
    scale: 3.6,
    cooldown: 16,
    quality: 'purple',
    icon: 'orb',
    targets: 2,
    desc: '献祭三成当前生命，化作血光爆发，对两名敌人造成 360% 魂伤。',
    unlockStage: 50,
  },
  {
    id: 'tr_youming_lamp',
    name: '幽冥灯',
    kind: 'active',
    cast: 'dot',
    damageType: 'soul',
    scale: 1.4,
    cooldown: 10,
    quality: 'green',
    icon: 'lamp',
    duration: 8,
    desc: '一盏幽灯照魂，持续灼蚀敌人神魂，并削弱其防御与回复。',
    unlockStage: 15,
  },
  {
    id: 'tr_yinyang_mirror',
    name: '阴阳镜',
    kind: 'active',
    cast: 'buff',
    damageType: 'true',
    scale: 1.2,
    cooldown: 24,
    quality: 'orange',
    icon: 'mirror',
    desc: '镜分阴阳，映照前尘。复制六息内施放过的最近一个主动法宝。',
    unlockStage: 100,
  },
  {
    id: 'tr_baigu_tower',
    name: '白骨塔',
    kind: 'active',
    cast: 'summon',
    damageType: 'soul',
    scale: 2.4,
    cooldown: 14,
    quality: 'purple',
    icon: 'tower',
    targets: 2,
    duration: 12,
    desc: '白骨垒塔，傀影自行。召出一具骨傀替身，持续缠住敌人并承受伤害。',
    unlockStage: 60,
  },

  /* ------------------------------ 通用 9 ------------------------------ */
  {
    id: 'tr_qingmu_gourd',
    name: '青木葫芦',
    kind: 'active',
    cast: 'heal',
    damageType: 'wood',
    scale: 1.6,
    cooldown: 12,
    quality: 'green',
    icon: 'gourd',
    desc: '葫芦倾出灵液，回复自身生命，并在一段时间内提升木系恢复。',
    unlockStage: 20,
  },
  {
    id: 'tr_dingfeng_bead',
    name: '定风珠',
    kind: 'passive',
    cast: 'aura',
    damageType: 'water',
    scale: 0,
    cooldown: 0,
    quality: 'white',
    icon: 'bead',
    desc: '常驻提升控制抗性，并使攻速不再被减速类效果打乱。',
    unlockStage: 25,
  },
  {
    id: 'tr_qiankun_ring',
    name: '乾坤环',
    kind: 'active',
    cast: 'aoe',
    damageType: 'earth',
    scale: 1.5,
    cooldown: 8,
    quality: 'blue',
    icon: 'ring',
    targets: 5,
    desc: '环转乾坤，聚散由心。将散落敌人聚拢并造成 150% 范围伤害。',
    unlockStage: 35,
  },
  {
    id: 'tr_zhenhun_bell',
    name: '镇魂铃',
    kind: 'active',
    cast: 'buff',
    damageType: 'soul',
    scale: 1.3,
    cooldown: 15,
    quality: 'purple',
    icon: 'bell',
    targets: 4,
    duration: 5,
    desc: '铃音一响，神魂俱定。压制敌方召唤物与亡魂，使其无法行动。',
    unlockStage: 55,
  },
  {
    id: 'tr_xingluo_compass',
    name: '星罗盘',
    kind: 'passive',
    cast: 'aura',
    damageType: 'true',
    scale: 0,
    cooldown: 0,
    quality: 'blue',
    icon: 'compass',
    desc: '常驻小幅提升奇遇与稀有掉落概率，罗盘指针总是指向机缘所在。',
    unlockStage: 45,
  },
  {
    id: 'tr_xuantian_ruler',
    name: '玄天尺',
    kind: 'active',
    cast: 'projectile',
    damageType: 'physical',
    scale: 3.8,
    cooldown: 15,
    quality: 'orange',
    icon: 'ruler',
    desc: '尺量生死，缺失愈多杀伤愈重。目标每少一成生命，伤害提升一成。',
    unlockStage: 80,
  },
  {
    id: 'tr_lingshou_ring',
    name: '灵兽环',
    kind: 'passive',
    cast: 'aura',
    damageType: 'true',
    scale: 0,
    cooldown: 0,
    quality: 'purple',
    icon: 'ring',
    desc: '常驻降低灵兽技能冷却，并小幅提升灵兽造成的伤害。',
    unlockStage: 70,
  },
  {
    id: 'tr_tiangang_shield',
    name: '天罡盾',
    kind: 'passive',
    cast: 'shield',
    damageType: 'earth',
    scale: 0,
    cooldown: 0,
    quality: 'blue',
    icon: 'shield',
    desc: '每十二息自行凝出一层天罡护盾，破而复生。',
    unlockStage: 40,
  },
  {
    id: 'tr_juling_bottle',
    name: '聚灵瓶',
    kind: 'passive',
    cast: 'aura',
    damageType: 'true',
    scale: 0,
    cooldown: 0,
    quality: 'white',
    icon: 'bottle',
    desc: '常驻提升修为获取与灵力回复，挂机时亦自行纳灵。',
    unlockStage: 15,
  },

  /* ------------------------------ 主线 ------------------------------ */
  {
    id: 'tr_canpo_guyu',
    name: '残缺古玉',
    kind: 'passive',
    cast: 'aura',
    damageType: 'true',
    scale: 0,
    cooldown: 0,
    quality: 'rainbow',
    icon: 'jade',
    desc: '问道界玦的碎片，剧情之钥。不占普通法宝栏，共鸣越深，越能照见天门。',
    unlockStage: 1,
  },
]

export const TREASURE_BY_ID: Record<string, TreasureDef> = Object.fromEntries(
  TREASURES.map((t) => [t.id, t]),
)

/** 主线法宝 id，用于判断是否占用 5+2 法宝栏位 */
export const MAINLINE_TREASURE_ID = 'tr_canpo_guyu'
