import {
  Amphora,
  Anvil,
  Axe,
  BookOpen,
  Boxes,
  Castle,
  CircleDot,
  Coins,
  Compass,
  Crown,
  Diamond,
  Droplet,
  Feather,
  Flag,
  Flame,
  FlameKindling,
  FlaskConical,
  Flower,
  Footprints,
  Funnel,
  Gem,
  Gift,
  Hand,
  Heart,
  Hexagon,
  House,
  Landmark,
  Layers,
  Leaf,
  Library,
  Map,
  Package,
  PawPrint,
  Pickaxe,
  Pill,
  Ruler,
  Scroll,
  Shield,
  Shirt,
  Sparkles,
  Sprout,
  Stamp,
  Store,
  Sword,
  Ticket,
  TreePine,
  Trophy,
  Turtle,
  User,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const REGISTRY: Record<string, LucideIcon> = {
  sword: Sword,
  talisman: Ticket,
  wind: Wind,
  banner: Flag,
  thunder: Zap,
  seal: Stamp,
  tortoise: Turtle,
  crown: Crown,
  robe: Shirt,
  belt: Ruler,
  bracer: Hand,
  boots: Footprints,
  necklace: Gem,
  ring: CircleDot,
  jade: Diamond,
  ore: Pickaxe,
  wood: TreePine,
  orb: CircleDot,
  crystal: Gem,
  pill: Pill,
  scroll: Scroll,
  token: Coins,
  pouch: Package,
  book: BookOpen,
  array: Hexagon,
  furnace: FlameKindling,
  anvil: Anvil,
  field: Sprout,
  beast: PawPrint,
  library: Library,
  shop: Store,
  gate: Landmark,
  map: Map,
  user: User,
  vase: Amphora,
  flame: Flame,
  gift: Gift,
  lotus: Flower,
  heart: Heart,
  shield: Shield,
  spark: Sparkles,
  burst: Zap,
  feather: Feather,
  drop: Droplet,
  axe: Axe,
  filter: Funnel,
  home: House,
  castle: Castle,
  layers: Layers,
  compass: Compass,
  leaf: Leaf,
  boxes: Boxes,
  flask: FlaskConical,
  trophy: Trophy,
}

export function GameIcon({
  name,
  className,
  strokeWidth = 1.6,
}: {
  name: string
  className?: string
  strokeWidth?: number
}) {
  const Icon = REGISTRY[name] ?? Sparkles
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden="true" />
}
